### ISSUE TITLE
API: send med brukernavn når vi connecter

### ISSUE THREAD

**Issue by Desarc** [Sankra/DIRC#6]

**Comment by Desarc** [comment]
Trengs for å løse https://github.com/Sankra/DIRC/issues/5 på en fornuftig måte

**Comment by Hammerstad** [comment]
Yeah, men skal vi beynne med state på server da?
Keep it simple?

**Comment by Desarc** [comment]
trenger nok en connectionId <-> username mapping på server. i utgangspunktet vet server (og andre) bare connectionId (guid) når noen logger på, username blir ikke kjent før man har sendt en melding.

**Comment by Desarc** [comment]
commit 01d75611ee6adec9112be97b9f3486a89db2f88a
